language: node_js
node_js:
- stable
cache:
  directories: 
    - node_modules
env:
  global:
  - DEPLOY_PORT=18765
  - secure: "HN1VplxFPFks85ewgN4Rbun3KuGHgmGainLhNwivOk69loHHr2a7SbTkiLFoK7Uzi/awrM9TlJuJETMK26okn3ANecXMSwjEnNlwVxo/k1MsOp3L4b2Zz0ZXc3IouTKe4kzS2YrKPPtrah0cuPqzvRMu/ityZ+0HDIp5AR8rVqPBEM8IRW4RAScwGlIirr0NlX+ypcgcoHwE9a3D+vn0i5cLMl8AVcLN8IkyDwv00XHiALfbeeyaG2hlBy/WJEumRwJ7mnnhzvxnrERw2EzY4AJQ5xCQNq8ODz29Zrn2hV6RPKZ5nhWC0v39h5zx6PJc869bvdZGy00jI+nDbKDeBEEHocIozpdI2FKgPs3EKdaGl/e4vE5ioFUoX9Zr1rPfYw0eyRRTKcjP7othZavX+ExWVAL3hzcuhvDZPHgvrErtYKWzwk9JOY95iOYLVCmNjR12tIu62zauI1AksmAb/G4nQ1VBTzvLnCfCMWtBhhJgIkMRCytIgz4J4Ih5BxZJVTyyb1/BWNS1avWAspdY1BaeCc+SAiej/KG39c+FXUjhIIIDqPw5RQw322mBITSrUGxV8BLjHZ9X5iaHYN+Ss5bp0p1o71xp9G3JC3dEvwj3UXiKJLqP6irhWJWC9PoByQ/xwtjTnKVdHisbmt6BY3XdBlmuE671PsVm8CeFXc8="
  - secure: "R8UxjbciNKCnmsm4EQE1cjbL1r/y/nsZ17ePLPR85PkL59VQx6nleEUDkyo7aXpck93ZHlcWb/dt4JhZhglJ1gXGSk62RaTkfxpoH1sM+VoM+CVNKZ3xM+DeF58wBNiYT0kl8ywrsKHpZYE3y9Hm/mStHqGKrcsKIl/qLBbJy7WYvExiI2E9G7QOY0CbLk9TbBfvyb+cZrf0auoMS/ghJQ5k8+rls4RpU99ScksgB1aPGv+HD2mwtbzy6b7DtEipjjRtkPJ9PbJUKP+4wmmHMwJoJVuUO/0CqAyKqrXoTl55Xu/t0hAuxpnguGNVToVxvhpk9QcbsZwacB1LDL3hWcrwi90tXDfAEcfqMi2w9sf1fcOB1RZTpELtkX1trbuaiTrjMFDs5cohcV/UiIwp9gIfMpCX1e/OlSxHJf1zWgc8+/ywVYFfUnnqaipE6VTldJbqAij/JcTNWsaGZ8ux5N16iHCveahS7Jhxa5NQO/pPOGlrtZoarOxeY+i7n30kWsYb8OovZz77keyuO1e0RtrrQZU4eE0YKa8IQb0qw/LmjMB7B/tdM5eixMCaa8npTWtfoqNpZezKStahAb/iy24BW42vhYQBRsK5UFgkgEPpUWnJipFjeaue830A0SOU+G0S10cZY06ma6FrV/ErrfvfUKsmOgANGWG39XBHrKY="
  - secure: "mMyIHCBM90ZRMKDfoSz/6zxd99taUn2NrrvEhJ3n6NM9ceZ3ItF+9YqpLamgwOuyLZNAimvlg/Cr7hFSZ8YdRemx7CN4yhQv7nkLGg1TToBy3UZMZp/6GLHsUCEJgKCm7Z1LA+pIKpxnALsMf+/HHoc0lTyUG/AmrphT69yA6DrX+DKDThW3u8C8VJx3mDZaL32tMfWyTs2TGt0tYytjldQ6NDXMU0URIjacrufCUW+nZqf9/THUMXVsR9owUQkayxKCKRUOtz5klVeFTx4MBYX2gLay6FnIVJVpOpdx/DKKDThoeHl36drLnvdd24ii6Auo/Xo0+VAAjN87bSMGd9MvTcl/gBcx1bE1cDVEB/O1/hljy0EcxtyUHBndt8ckLv4nvQ/iwVuwba18FC5kf0uc9WzEW9WC9Ap5oafnIOcLVKhuh793fLvPBJhdXfyxrYSeAoxa24k0PS/EAfJfPfkAjs/WxaXjJLbqPg2bPsqP1929fpJX2lbwrXbzZQGtx6NENjpCmterr8R5xYmfxj4fap46l9oVcVsN+xYZ+hB0bK1lyRgEaVPqa+J3bfahcLVgeoiOTDXSzlNOgPUDc3QiNwfPu40JHSiwhXziq+BxHSZsk92PNZVQbby/yFsGFUsW6eSzqHuINY5c5uQbPMmrPJjw/gOLoLx8xVrIJOw="
script: 
  - npm run build
  - npm test
before_deploy:
  - openssl aes-256-cbc -K $encrypted_602f0584601e_key -iv $encrypted_602f0584601e_iv -in ./deploy/deploy.enc -out /tmp/deploy -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy
  - ssh-add /tmp/deploy
  - rm /tmp/deploy
deploy:
  - provider: script
    skip_cleanup: true
    script: bash ./deploy/deploy.sh staging
    on:
      branch: staging
  - provider: script
    skip_cleanup: true
    script: bash ./deploy/deploy.sh production
    on:
      branch: main
